### ISSUE TITLE
Tasks for Monday

### ISSUE THREAD

**Issue by IgorBaratta** [Excalibur-SLE/wave-fenics#1]
- [x] Spack on Baskerville [@chrisrichardson]
- [x] Prepare presentation [@adeebkor , @IgorBaratta ]
- [x] Add cpu mini-app to repository [@adeebkor]
- [x] Add gpu operators [@IgorBaratta ]

**Comment by chrisrichardson** [comment]
`fenics-dolfinx` is now installed on **baskerville**.
Files are in our shared project folder `/bask/projects/m/mhdz1996-wavefenics`.

You need to have a *compute node* to compile anything. You should first do something like:
`salloc --qos=epsrc --time=4:0:0` to get a login to a compute node.

To use:
```
module load OpenMPI
source /bask/projects/m/mhdz1996-wavefenics/spack/share/spack/setup-env.sh
spack load fenics-dolfinx
spack load cmake
```
I have compiled and run the 'performance-test'.

**Comment by IgorBaratta** [comment]
I will open some more issues with updated tasks.
